web_exercise/apps/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    # 登录,注册
    url(r'^login/$', views.Login.as_view(), name="login"),
    # 退出
    url(r'^logout/$', views.Logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.PasswordForget.as_view(), name="password_forget"),
    # 重置密码
    url(r'password/reset/(\w+)/$', views.PasswordReset.as_view(), name="password_reset"),

]

web_exercise/apps/apis/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 获取手机验证码
    url(r'^mobile_captcha/$', views.get_mobile_captcha, name='get_mobile_captcha'),
    # 获取图片验证码
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    # 验证图片验证码
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),
    # 上传头像
    url(r'^change_avator/$', views.ChangeAvator.as_view(), name='change_avator'),

]

web_exercise/apps/diet/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^center/$', views.Center, name="center"),
    url(r'^single/$', views.single, name="single"),

]

web_exercise/apps/exercise/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    # 首页
    url(r'^index/$', views.index.as_view(), name="index"),
    # 健身部位
    url(r'^index/(?P<id>\d+)/$', views.IndexDetail.as_view(), name="indexDetail"),
    # 部位
    url(r'^part/$', views.part, name="part"),

]

web_exercise/web_exercise/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from .settings import MEDIA_ROOT
from . import views

urlpatterns = [
    # admin用户
    url(r'^admin/', admin.site.urls),
    # media 处理路由
    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # 首页
    url(r'^exercise/', include('apps.exercise.urls', namespace="exercise")),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    url(r'^slimming/', include('apps.slimming.urls', namespace="slimming")),
    url(r'^schedule/', include('apps.schedule.urls', namespace="schedule")),
    url(r'^equipments/', include('apps.equipments.urls', namespace="equipments")),
    url(r'^diet/', include('apps.diet.urls', namespace="diet")),
    url(r'^uc/', include('apps.usercenter.urls', namespace="uc")),
]

web_exercise/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}base{% endblock %}</title>
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
{#<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />#}

{% block load_css %}
{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fitness Zone Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>


</head>
<body>
	<!-- header-section-starts -->
	<div class="header-top">
		<div class="logo text-center">
			<h1><a href="{% url 'exercise:index' %}">Fitness Zone</a></h1>
		</div>
		<!-- navigation -->
		<div class="navigation">
			<div class="container">
                <nav class="navbar navbar-default">

					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% url 'exercise:index' as ct_index %}
                            {% url 'slimming:center' as ct_slimming %}
                            {% url 'schedule:center' as ct_schedule %}
                            {% url 'equipments:center' as ct_equipments %}
                            {% url 'diet:center' as ct_diet %}
                            {# {% url 'usercenter:center' as ct_usercenter %} #}

							<li class="hvr-bounce-to-bottom {% if current_url == ct_index %}active{% endif %}"><a href="{{ ct_index }}">首页 <span class="sr-only">(current)</span></a></li>
							<li class="hvr-bounce-to-bottom {% if current_url == ct_slimming %}active{% endif %}"><a href="{{ ct_slimming }}">减肥</a></li>
							<li class="hvr-bounce-to-bottom {% if current_url == ct_schedule %}active{% endif %}"><a href="{{ ct_schedule }}">计划</a></li>
							<li class="hvr-bounce-to-bottom {% if current_url == ct_equipments %}active{% endif %}"><a href="{{ ct_equipments }}">器材</a></li>
							<li class="hvr-bounce-to-bottom {% if current_url == ct_diet %}active{% endif %}"><a href="{{ ct_diet }}">饮食</a></li>
                            {# <li class="hvr-bounce-to-bottom {% if current_url == ct_usercenter %}active{% endif %}"><a href="{{ ct_usercenter }}">用户中心</a></li>#}
                            {% if user.is_authenticated %}
                            <li class="hvr-bounce-to-bottom">
                                <ul class="nav navbar-nav">
                                    <div class="btn-group" role="group" aria-label="...">

                                        <div class="btn-group" role="group">
                                            <button type="button" class="btn btn-default dropdown-toggle " id="button-color" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 94.5px;height: 49px;">
                                                {{ user }}用户
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a href="{% url 'uc:profile' %}">个人资料</a></li>
                                                <li><a href="{% url 'uc:change_passwd' %}">修改密码</a></li>
                                                <li><a href="#">我的收藏</a></li>
                                                <li><a href="{% url 'accounts:logout' %}">退出</a></li>
                                            </ul>
                                        </div>
                                        <button type="button" class="btn btn-default " id="button-color" style="width: 96px;height: 49px"><a style="font-size: 1.1em;color: black" href="{% url 'accounts:logout' %}">注销</a></button>
                                    </div>
                                </ul>
                            {% else %}
                                <ul class="nav navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link login-button  glyphicon glyphicon-user" id="button-color" href="{% url 'accounts:login' %}">&nbsp;登录</a>
                                    </li>
                                </ul>
                            {% endif %}
                            </li>
						</ul>
                        <div class="clearfix"></div>
					</div>
				</nav>
			</div>
		</div>
		<!-- //navigation -->
		<div class="clearfix"></div>
	</div>


    {% block content %}这是BASE页面{% endblock %}


    <div class="footer">
		<div class="container">
			<div class="copyright text-center">
				<p> &copy; 2019.August.</p>
			</div>
		</div>
	</div>
	<!-- footer-section -->

	<a href="#to-top" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block load_js %}
    {% endblock %}
    <script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
    </script>
    <script type="text/javascript">
		$(document).ready(function() {
				/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
				*/
				$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>

</body>
<style>
    #button-color:hover{
        background-color: #f94877;
    }
</style>
</html>

web_exercise/templates/diet_center.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block load_css %}
{% endblock %}

<title>{% block title %}diet{% endblock %}</title>

{% block content %}
    <div class="inner-banner"></div>

    <div class="blog-section">
	    <div class="container">
		<h2 class="heading text-center">Blogs</h2>
		<div class="blog-post-grids">
			<div class="blog-post">
					<a href="{% url 'diet:single' %}"><img src="{% static 'images/b1.jpg' %}" class="img-responsive" alt="  "/></a>
					<div class="text">
						<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
					</div>
					<div class="admin-tag">
					<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
					<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
					nulla, sodales quis posuere quis, tristique nec libero. Proin
					vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
					<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
					</div>
			</div>
			<div class="blog-post">
					<a href="{% url 'diet:single' %}"><img src="{% static 'images/b2.jpg' %}" class="img-responsive" alt="  "/></a>
					<div class="text">
						<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
					</div>
					<div class="admin-tag">
					<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
					<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
					nulla, sodales quis posuere quis, tristique nec libero. Proin
					vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
					<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
					</div>
			</div>
		</div>
		<div class="blog-post-grids">
			<div class="blog-post">
				<a href="{% url 'diet:single' %}"><img src="{% static 'images/b3.jpg' %}" class="img-responsive" alt="  "/></a>
				<div class="text">
					<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
				</div>
				<div class="admin-tag">
				<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
				<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
				nulla, sodales quis posuere quis, tristique nec libero. Proin
				vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
				<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
				</div>
			</div>
			<div class="blog-post">
				<a href="{% url 'diet:single' %}"><img src="{% static 'images/b4.jpg' %}" class="img-responsive" alt="  "/></a>
				<div class="text">
					<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
				</div>
				<div class="admin-tag">
				<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
				<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
				nulla, sodales quis posuere quis, tristique nec libero. Proin
				vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
				<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
				</div>
			</div>
		</div>
		<div class="blog-post-grids">
			<div class="blog-post">
				<a href="{% url 'diet:single' %}"><img src="{% static 'images/b4.jpg' %}" class="img-responsive" alt="  "/></a>
				<div class="text">
					<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
				</div>
				<div class="admin-tag">
				<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
				<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
				nulla, sodales quis posuere quis, tristique nec libero. Proin
				vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
				<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
				</div>
			</div>
			<div class="blog-post">
				<a href="{% url 'diet:single' %}"><img src="{% static 'images/b1.jpg' %}" class="img-responsive" alt="  "/></a>
				<div class="text">
					<a href="{% url 'diet:single' %}"> Aliquam erat volutpat</a>
				</div>
				<div class="admin-tag">
				<p>Posted by <a href="{% url 'diet:single' %}">Admin</a> in <a href="#">General</a> | <a href="{% url 'diet:single' %}">10 Comments</a></p>
				<p class="erat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Nulla in purus nibh. Donec ornare felis neque. Nullam tortor
				nulla, sodales quis posuere quis, tristique nec libero. Proin
				vitae convallis odio. Morbi nec enim nisi. Aliquam erat volutpat.</p>
				<a href="{% url 'diet:single' %}" class="hvr-shutter-in-horizontal more">Readmore<span> </span></a>
				</div>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>
	    <!--start-news-pagenate-->
        <div class="blog-pagenat">
            <ul>
                <li><a class="frist" href="#">Prev</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">6</a></li>
                <li><a class="last" href="#">Next</a></li>
            </ul>
        </div>
        <!--//End-news-pagenate-->
    </div>
{% endblock %}

{% block load_js %}
{% endblock %}

web_exercise/templates/login_register.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Web_Exercise</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-1.9.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
    <link href="{% static 'css/login2.css' %}" rel="stylesheet" type="text/css"/>

    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>

</head>
<body>


<div class="login" style="margin-top:200px; margin-right: 250px">
    <div class="header">
        <div class="switch" id="switch"><a class="switch_btn_focus" id="switch_qlogin" href="javascript:void(0);"
                                           tabindex="7">快速登录</a>
            <a class="switch_btn" id="switch_login" href="javascript:void(0);" tabindex="8">快速注册</a>
            <div class="switch_bottom" id="switch_bottom" style="position: absolute; width: 64px; left: 0px;"></div>

        </div>
    </div>

    <div class="web_qr_login" id="web_qr_login" style="display: block; height: 300px;">
        <!--登录-->
        <div class="web_login" id="web_login">
            <div class="login-box">
                <div class="login_form">
                    <form name="loginform" accept-charset="utf-8" id="login_form" class="loginForm"
                          method="post">
                        {# 隐藏域 #}
                        <input type="hidden" name="did" value="0"/>
                        <input type="hidden" name="msg" value="2"/>
                        {% csrf_token %}
                        <div class="uinArea" id="uinArea">
                            <label class="input-tips" for="u">用户名：</label>
                            <div class="inputOuter" id="uArea">
                                {# <input type="text" id="u" name="username" class="inputstyle"/> #}
                                {{ forms.username }}
                            </div>
                        </div>
                        <div class="pwdArea" id="pwdArea">
                            <label class="input-tips" for="p">密码：</label>
                            <div class="inputOuter" id="pArea">
                                {# <input type="password" id="p" name="p" class="inputstyle"/> #}
                                {{ forms.password }}
                            </div>
                        </div>
                        <div id="pwdArea">
                            <label class="input-tips" for="captcha">验证码：</label>
                            <div style="position: relative;margin-top: -5px">
                                {# <input type="text" id="captcha" name="captcha" class="inputstyle"/> #}
                                {{ forms.captcha }}
                                <a href="javascript:void(0);"><img id="captcha_img" src="#" style="width: 100px;height: 40px;top:15px;position: relative"> </a>
                            </div>
                        </div>
                        <div class="user-reg" style="margin-top: 10px">
                            <span class="pull-right"> <a href="{% url 'accounts:password_forget' %}" style="margin-left: 200px;"> 忘记密码?</a></span>
                        </div>
                        <div style="padding-left:50px;margin-top:20px;">
                        <button style="width:150px; margin-left: 30px" type="button" id="submit" class="button_blue">登录</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--登录end-->
    </div>

    <!--注册-->
    <div class="qlogin" id="qlogin" style="display: none; ">
        <div class="web_login">
            <form name="form2" id="regUser" accept-charset="utf-8" method="post">
                {% csrf_token %}
                <input type="hidden" name="msg" value="1"/>
                <input type="hidden" name="did" value="0"/>
                <ul class="reg_form" id="reg-ul">
                    <div id="userCue" class="cue">快速注册请注意格式</div>
                    <li>
                        <label for="user" class="input-tips2">用户名：</label>
                        <div class="inputOuter2">
                            {{ form.username }}
                        </div>
                    </li>
                    <li>
                        <label for="passwd" class="input-tips2">密码：</label>
                        <div class="inputOuter2">
                            {{ form.password }}
                        </div>
                    </li>
                    <li>
                        <label class="input-tips2">确认密码：</label>
                        <div class="inputOuter2">
                            {{ form.password2 }}
                        </div>
                    </li>
                    <li>
                        <label for="mobile" class="input-tips2">手机：</label>
                        <div class="inputOuter2">
                            {{ form.mobile }}
                        </div>
                    </li>
                    <li>
                        <label for="mobile_captcha" class="input-tips2">验证码：</label>
                        <div class="inputOuter2">
                            {{ form.mobile_captcha }}
                            <input onclick="sendmessage(this,60);" type="button" value="发送短信" class="btn btn-info"
                                   style="height:40px;width: 86px;"/>
                        </div>
                    </li>
                    <li>
                        <div class="inputArea">
                            <input type="button" id="reg" style="margin-top:10px;margin-left:85px;" class="button_blue"
                                   value="同意协议并注册"/>
                        </div>
                    </li>
                    <div class="cl"></div>
                </ul>
            </form>
        </div>
    </div>
    <!--注册end-->


    {# 添加js动作,短信验证码#}
    <script>
        {# 发送短信验证码，点击发送短信就调用函数sendmessage #}
        function sendmessage(obj, second) {
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if (telRegex.test($.trim($("#mobile").val()))) {
                $.ajax({
                    url: "{% url 'apis:get_mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#mobile").val()},
                    success: function (data) {
                        {#提示小工具gritter#}
                        $.gritter.add({
                            title: '提交结果',
                            text: data.msg
                        });
                    }
                });
                {#倒计时#}
                countDown(obj, second)
            } else {
                $.gritter.add({
                    title: '提交结果',
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj, second) {
            // 如果秒数还是大于0，则表示倒计时还没结束
            if (second >= 0) {
                // 获取默认按钮上的文字
                if (typeof buttonDefaultValue === 'undefined') {
                    buttonDefaultValue = obj.defaultValue;
                }
                // 按钮置为不可点击状态
                obj.disabled = true;
                // 按钮里的内容呈现倒计时状态
                obj.value = buttonDefaultValue + '(' + second + ')';
                // 时间减一
                second--;
                // 一秒后重复执行
                setTimeout(function () {
                    countDown(obj, second);
                }, 1000);
                // 否则，按钮重置为初始状态
            } else {
                // 按钮置未可点击状态
                obj.disabled = false;
                // 按钮里的内容恢复初始状态
                obj.value = buttonDefaultValue;
            }
        }
    </script>

    {# 注册按钮的js #}
    <script>
        $("#reg").click(function () {
            // 把序列化的值传给ajax()作为url的参数
            console.log($("#regUser").serialize());
            $.ajax({
                url: "{% url 'accounts:login' %}",
                type: "POST",
                dataType: "json",
                data: $("#regUser").serialize(),
                success: function (data) {
                    if (data.status == 200) {
                        {#刷新页面#}
                        window.location.href = "{% url 'exercise:index' %}";
                    } else {
                        msg = "新错误类型"
                        if (data.status == 400 || data.status == 401) {
                            msg = data.msg
                        } else {
                            for (var i in data.msg) {
                                msg = i + data.msg[i]
                                break
                            }
                        }
                        $.gritter.add({
                            title: '提交结果',
                            text: msg
                        });
                    }
                },
                // 解决csrftoken
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                }
            });
        });
    </script>

    {# 新加的登录按钮的js #}
    <script>
        $("#submit").click(function () {
            // some_check
            console.log($("#login_form").serialize());
            $.ajax({
                url: "{% url 'accounts:login' %}",
                type: "POST",
                dataType: "json",
                data: $("#login_form").serialize(),
                success: function (data) {
                    console.log(data);
                if(data.status == 200)
            {
                {#刷新页面#}
                window.location.href = "{% url 'exercise:index' %}";
            }
        else
            {
                msg = "新错误类型"
                if (data.status == 400 || data.status == 401) {
                    msg = data.msg
                } else {
                    for (var i in data.msg) {
                        msg = i + data.msg[i]
                        break
                    }
                }
                $.gritter.add({
                    title: '提交结果',
                    text: msg
                });
            }
        },
            // 解决csrftoken
            beforeSend: function(xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            }
        });
        });
    </script>

    {# 点击验证码图片后，Ajax动态验证码 #}
    <script>
        get_captcha_img();
        $("#captcha_img").click(get_captcha_img);

        function get_captcha_img() {
            $.ajax({
                url: '{% url 'apis:get_captcha' %}',
                type: 'GET',
                dataType: 'text',
                success: function (data) {
                    $('#captcha_img').attr('src', data);
                }
            });
        }
         {# ajax动态检查验证码 #}
        // 这里在form中定义了，如果没定义可以用jquery添加事件
        // $("#id_captcha").blur(check_captcha);

        // 当失去焦点时检查验证码
        function check_captcha() {
            var captcha_code = $('#captcha').val();
            if (captcha_code.length == 0) {
                return false
            }
            $.ajax({
                url: '{% url 'apis:check_captcha' %}',
                type: 'GET',
                dataType: 'json',
                data: {"captcha_code": captcha_code},
                success: function (data) {
                    if (data.code == 400) {
                        $('.msg').html("验证码错误");
                    } else {
                        $('.msg').html("");
                    }
                }
            });
        };
    </script>
</div>
</body>
</html>

web_exercise/templates/password_forget.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block load_css %}
{% endblock %}

<title>{% block title %}Email{% endblock %}</title>

{% block content %}
    <div class="inner-banner"></div>
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-body">
                <h2 class="heading text-center">请输入绑定的邮箱</h2>
                <hr/>
                <div class="col-md-7 col-lg-7 col-sm-7">
                    <form class="form-horizontal" style="position: relative; margin-left: 50%" role="form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="inputPasswordOld" class="col-lg-3 control-label">邮箱</label>
                            <div class="col-lg-9">
                                <input name="email" type="email" class="form-control" id="inputPasswordOld" placeholder="邮箱" required>
                            </div>
                        </div>
                        <div class="form-group">
                              <div class="col-lg-offset-3 col-lg-9">
                                  <button type="submit" class="btn btn-danger">提交</button>
                              </div>
                        </div>
                     </form>
                </div>
          </div>
        </div>
    </div>
{% endblock %}

<div style="">

</div>